apiVersion: apps/v1
kind: Deployment
metadata:
  name: eddiebot-deployment
  labels:
    app: eddiebot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eddiebot
  template:
    metadata:
      labels:
        app: eddiebot
    spec:
      volumes:
        - name: mongo-crt
          secret:
            secretName: mongo-crt
      containers:
        - name: eddiebot
          image: ghcr.io/eddiehubcommunity/eddiebot:latest
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: '/etc/mongo/crt'
              name: mongo-crt
              readOnly: true
          env:
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: discord-token
                  key: DISCORD_TOKEN
            - name: EDDIEBOT_MONGO_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: eddiebot-mongo-connection-string
                  key: EDDIEBOT_MONGO_CONNECTION_STRING
            - name: HOME_GUILD
              valueFrom:
                secretKeyRef:
                  name: home-guild
                  key: HOME_GUILD
