apiVersion: apps/v1
kind: Deployment
metadata:
  name: eddiebot-deployment
  labels:
    app: eddiebot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eddiebot
  template:
    metadata:
      labels:
        app: eddiebot
    spec:
      containers:
      - name: eddiebot
        image: ghcr.io/eddiehubcommunity/eddiebot:latest
        imagePullPolicy: Always
        env:
          - name: DISCORD_BOT_TOKEN
            valueFrom:
              secretKeyRef:
                name: discord-bot-token
                key: DISCORD_BOT_TOKEN
          - name: DISCORD_PREFIX
            valueFrom:
              secretKeyRef:
                name: discord-bot-prefix
                key: DISCORD_BOT_PREFIX
