apiVersion: apps/v1
kind: Deployment
metadata:
  name: eddiebot-deployment
  labels:
    app: eddiebot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eddiebot
  template:
    metadata:
      labels:
        app: eddiebot
    spec:
      containers:
        - name: eddiebot
          image: ghcr.io/eddiehubcommunity/eddiebot:latest
          imagePullPolicy: Always
          env:
            - name: DISCORD_TOKEN
              valueFrom:
                secretKeyRef:
                  name: discord-token
                  key: DISCORD_TOKEN
            - name: DISCORD_PREFIX
              valueFrom:
                secretKeyRef:
                  name: discord-prefix
                  key: DISCORD_PREFIX
            - name: API_URL
              valueFrom:
                secretKeyRef:
                  name: api-url
                  key: API_URL
            - name: API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: api-token
                  key: API_TOKEN
