# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
    - name: Install deps and build project
      run: |
        npm ci
        npm run build --if-present
    - name: Setup private secrets
      run: sed -i 's|{{ DISCORD_TOKEN }}|'"${{ secrets.DISCORD_TOKEN }}"'|g' app.yml
    - name: Deploy to gcloud
      run: |
        echo ${{ secrets.DEPLOY_KEY_FILE }} > /tmp/deploy_key_file.json
        gcloud auth activate-service-account --key-file /tmp/deploy_key_file.json
        gcloud config set project $GCLOUD_PROJECT
        gcloud info
